modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "CC0"

[[mods]]
modId = "mobspawnlimit"
version = "${version}"
displayName = "MobSpawnLimit Mod"
authors = "Sistr"
description = "モブスポーン数制限Mod"
logoFile = "assets/mobspawnlimit/icon.png"

[[dependencies.mobspawnlimit]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobspawnlimit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobspawnlimit]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.51,)"
ordering = "AFTER"
side = "BOTH"